spanTime: 1200

debug: false

showcase:
  chest:
    material: CHEST
    repeat: 0
    spanTime: 1200
    pourcentToSpawn: 0.2
    firework: true
    particleSpawn: true
    rewards:
    # - currency:amount:multiplicator
      - explorer:50:10
    case:
       - world:0:0:0:NORTH

  enderchest:
    material: ENDER_CHEST
    repeat: 0
    spanTime: 1200
    pourcentToSpawn: 0.5
    firework: true
    particleSpawn: true
    rewards:
    case:
       - world:0:0:0:NORTH

  armorstand:
    material: ARMOR_STAND
    repeat: 1
    spanTime: 0
    pourcentToSpawn: 1.0
    firework: false
    particleSpawn: false
    rewards:
    case:
       - world:0:0:0:90